module(..., package.seeall)

--region capital coordinates list
region_capital_coord_list = {
	["acadia"] = {-473.89999, 326.79999},
	["afghanistan"] = {491.84, 245.56799},
	["ahmadnagar"] = {531.41302, 135.67999},
	["algiers"] = {21.55487, 258.36911},
	["algonquin_territory"] = {-557.59113, 305.651},
	["alsace"] = {55.1, 345.15811},
	["anatolia"] = {233.422, 282.453},
	["arkhangelsk"] = {284.853, 458.39099},
	["armenia"] = {316.185, 284.603},
	["astrakhan"] = {352.33801, 330.98001},
	["austria"] = {116.2016, 342.8577},
	["azerbaijan"] = {342.89999, 270.99899},
	["bahamas"] = {-547.65039, 175.58749},
	["baluchistan"] = {432.84, 209.74001},
	["bashkira"] = {397.48001, 387.90399},
	["bavaria"] = {83.4159, 342.19},
	["belarus"] = {195.78101, 381.879},
	["bengal"] = {628.12402, 158.8848},
	["berar"] = {561.99109, 149.89999},
	["bijapur"] = {527.38202, 125.24},
	["bohemia"] = {102.676, 357.25299},
	["bosnia"] = {130.53, 311.81},
	["bulgaria"] = {171.216, 305.02499},
	["carnatica"] = {564.51141, 91.733},
	["carolinas"] = {-569.8822, 234.4149},
	["ceylon"] = {574.65521, 60.02627},
	["chechenya-dagestan"] = {335.92099, 306.811},
	["cherokee_territory"] = {-603.35229, 252.2146},
	["corsica"] = {66.12566, 302.35529},
	["courland"] = {169.2506, 402.11041},
	["crimea"] = {241.564, 322.26099},
	["croatia"] = {113.628, 326.53101},
	["cuba"] = {-585.27667, 162.3866},
	["curacao"] = {-489.83221, 86.61607},
	["denmark"] = {84.31595, 394.62329},
	["don_voisko"] = {293.534, 335.6395},
	["dutch_guyana"] = {-392.39139, 40.37837},
	["egypt"] = {221.6741, 212.33611},
	["england"] = {0.774794578552246, 366.7189},
	["estonia_and_livonia"] = {174.96761, 406.6467},
	["finland"] = {152.7458, 429.72931},
	["flanders"] = {30.43247, 359.42679},
	["florida"] = {-579.75232, 212.05009},
	["france"] = {16.52293, 347.06699},
	["french_guyana"] = {-372.04599, 32.76262},
	["galicia"] = {170.56799, 353.185},
	["genoa"] = {64.004, 317.78601},
	["georgia"] = {318.866, 294.43671},
	["georgia_usa"] = {-577.52051, 226.7142},
	["gibraltar"] = {-38.65905, 258.96439},
	["great_plains"] = {-732.28308, 338.57031},
	["greece"] = {167.7124, 272.32239},
	["guatemala"] = {-644.39612, 103.204},
	["gujarat"] = {516.12402, 163.7},
	["hannover"] = {69.2048, 373.90619},
	["hindustan"] = {554.89301, 191.99001},
	["hispaniola"] = {-497.7309, 133.64281},
	["hungary"] = {122.5378, 343.7196},
	["huron_territory"] = {-598.16608, 330.66071},
	["hyderabad"] = {558.05103, 123.491},
	["iceland"] = {-153.9657, 457.54471},
	["ingria"] = {210.56911, 423.30481},
	["ireland"] = {-45.58778, 379.30789},
	["iroquois_territory"] = {-543.073, 305.293},
	["jamaica"] = {-549.83911, 129.04939},
	["kaintuck_territory"] = {-598.57452, 254.6088},
	["karelia"] = {243.61459, 440.30161},
	["kashmir"] = {531.84003, 242.41},
	["komi"] = {360.90399, 436.905},
	["labrador"] = {-430.06851, 393.18951},
	["leeward_islands"] = {-440.15591, 125.461},
	["lithuania"] = {179.564, 387.42899},
	["lower_louisiana"] = {-635.85638, 212.87781},
	["maine"] = {-500.76849, 311.71851},
	["malabar"] = {527.44598, 110.049},
	["malta"] = {101.701, 256.26971},
	["malwa"] = {538.85999, 163.4474},
	["maryland"] = {-545.60858, 276.3183},
	["mesopotamia"] = {314.19519, 238.11681},
	["michigan_territory"] = {-593.06958, 300.87531},
	["milan"] = {65.34001, 323.29999},
	["moldavia"] = {196.19, 335.38},
	["morea"] = {155.6821, 270.26151},
	["morocco"] = {-39.61066, 251.13361},
	["muscovy"] = {267.14899, 395.00201},
	["mysore"] = {543.80151, 86.60487},
	["naples"] = {104.0012, 291.81549},
	["netherlands"] = {35.91815, 373.49069},
	["new_andalusia"] = {-475.2803, 72.91182},
	["new_england"] = {-506.92941, 301.035},
	["new_france"] = {-506.25919, 335.20261},
	["new_grenada"] = {-528.86932, 34.00954},
	["new_mexico"] = {-752.56012, 252.69901},
	["new_spain"] = {-704.34003, 138.089},
	["new_york"] = {-525.18439, 302.84241},
	["newfoundland"] = {-381.09811, 336.63641},
	["northwest_territories"] = {-656.03198, 403.46799},
	["norway"] = {75.24967, 426.30551},
	["ontario"] = {-523.10681, 325.39581},
	["orissa"] = {608.14203, 144.142},
	["palestine"] = {249.24071, 225.5278},
	["panama"] = {-565.63458, 66.57263},
	["pennsylvania"] = {-535.88489, 285.9653},
	["persia"] = {365.60001, 230.63499},
	["poland"] = {150.5587, 370.26199},
	["portugal"] = {-62.98783, 276.98792},
	["prussia"] = {145.02789, 387.18439},
	["punjab"] = {528.56, 224.56},
	["rajpootana"] = {523.93988, 174.49001},
	["rhineland"] = {49.38722, 362.25931},
	["rumelia"] = {202.93629, 293.80521},
	["ruperts_land"] = {-571.23138, 364.97589},
	["sardinia"] = {65.74889, 280.84601},
	["savoy"] = {53.59999, 319.62381},
	["saxony"] = {96.05449, 364.34891},
	["scotland"] = {-19.84846, 395.8956},
	["serbia"] = {149.7117, 317.72391},
	["silesia"] = {120.3377, 363.03009},
	["sindh"] = {486.10999, 180.47},
	["spain"] = {-26.11482, 287.53711},
	["sweden"] = {125.5649, 421.7059},
	["syria"] = {260.93289, 234.1082},
	["tatariya"] = {350.91229, 396.00229},
	["tejas"] = {-699.59998, 208.64999},
	["the_papal_states"] = {89.34928, 298.9798},
	["transylvania"] = {172.75, 333.13},
	["trinidad_tobago"] = {-435.07309, 74.00154},
	["tripoli"] = {91.99881, 230.81419},
	["tunis"] = {70.37781, 261.40421},
	["ukraine"] = {217.9799, 359.19571},
	["upper_louisiana"] = {-635.14642, 271.8945},
	["venice"] = {87.41591, 325.40561},
	["virginia"] = {-546.64398, 265.37799},
	["west_pommerania"] = {94.76274, 374.42499},
	["west_prussia"] = {131.93739, 385.647},
	["windward_islands"] = {-434.25562, 104.1538},
	["wurttemberg"] = {63.78598, 346.48001},
}


-- list of all traits in the game
traitsList = {
	"C_Admiral_Attacker_Bad",
	"C_Admiral_Attacker_Good",
	"C_Admiral_Bad",
	"C_Admiral_Blockade_Runner_Good",
	"C_Admiral_Blockader_Good",
	"C_Admiral_Boring_Speaker",
	"C_Admiral_Born_Sailor",
	"C_Admiral_Brave",
	"C_Admiral_British_Drakes_Drum",
	"C_Admiral_Coward",
	"C_Admiral_Cruisers",
	"C_Admiral_Defender_Bad",
	"C_Admiral_Defender_Good",
	"C_Admiral_Drunkard",
	"C_Admiral_Dutch_Seamanship",
	"C_Admiral_Good",
	"C_Admiral_Lampooned",
	"C_Admiral_Mad",
	"C_Admiral_Martinet",
	"C_Admiral_Mathematician",
	"C_Admiral_Press_Hero",
	"C_Admiral_Rated_Ships",
	"C_Admiral_Slacker",
	"C_Admiral_Sobriety",
	"C_Admiral_Spanish_National_Pride",
	"C_Admiral_Swashbuckling",
	"C_Agent_Secret_Police",
	"C_Agent_Secret_Police",
	"C_Agent_Spy_Network",
	"C_Agent_Spy_Network",
	"C_Feck_Vice",
	"C_Feck_Vice",
	"C_Feck_Vice",
	"C_Feck_Vice",
	"C_Feck_Vice",
	"C_Feck_Vice",
	"C_Feck_Vice",
	"C_General_Ambush_Good",
	"C_General_Ambusher_Bad",
	"C_General_Americas_Bad",
	"C_General_Americas_Good",
	"C_General_Attacker_Bad",
	"C_General_Attacker_Good",
	"C_General_Austrian_Hates_Ottomans",
	"C_General_Bad_Field_Commander",
	"C_General_Bloody",
	"C_General_Born_Soldier",
	"C_General_Brave",
	"C_General_Coward",
	"C_General_Defender_Bad",
	"C_General_Defender_Good",
	"C_General_Drunkard",
	"C_General_French_Elan",
	"C_General_Good_Field_Commander",
	"C_General_India_Bad",
	"C_General_India_Good",
	"C_General_Lampooned",
	"C_General_Mad",
	"C_General_Marine_Bad",
	"C_General_Marine_Good",
	"C_General_Martinet",
	"C_General_Mughal_Anti_European",
	"C_General_of_Artillery",
	"C_General_of_Cavalry",
	"C_General_of_Infantry",
	"C_General_Polish_Stubborn",
	"C_General_Press_Hero",
	"C_General_Prussian_Blue",
	"C_General_Russian_Vodka",
	"C_General_Scout",
	"C_General_Siege_Attack_Bad",
	"C_General_Siege_Attack_Good",
	"C_General_Siege_Defend_Bad",
	"C_General_Siege_Defend_Good",
	"C_General_Slacker",
	"C_General_Swedish_Aggression",
	"C_General_Turkish_Master_Gunner",
	"C_General_US_Backwoodsman",
	"C_General_Warlord",
	"C_Gent_Academic_Honours",
	"C_Gent_Academic_Honours",
	"C_Gent_Duelling_Pistol",
	"C_Gent_Duelling_Sword",
	"C_Gent_Research_Agriculture",
	"C_Gent_Research_Agriculture",
	"C_Gent_Research_Economics",
	"C_Gent_Research_Economics",
	"C_Gent_Research_Industry",
	"C_Gent_Research_Industry",
	"C_Gent_Research_Military",
	"C_Gent_Research_Military",
	"C_Gent_Research_Navy",
	"C_Gent_Research_Navy",
	"C_Gent_Research_Philosophy",
	"C_Gent_Research_Philosophy",
	"C_Gent_Science_Club",
	"C_Honourable_Service",
	"C_Honourable_Service",
	"C_Leader_Agent_99",
	"C_Leader_Army_Buff",
	"C_Leader_Clever_Stick",
	"C_Leader_Debauched",
	"C_Leader_Dullard",
	"C_Leader_Enlightened_Despot",
	"C_Leader_Favourites",
	"C_Leader_Fertile",
	"C_Leader_Foreign_Tastes",
	"C_Leader_Harsh_Ruler",
	"C_Leader_Humanist",
	"C_Leader_Huntin_Shootin_Fishin",
	"C_Leader_Inbred",
	"C_Leader_Infertile",
	"C_Leader_Intellectual_Pretensions",
	"C_Leader_M",
	"C_Leader_Mad",
	"C_Leader_Merit",
	"C_Leader_Mr_Waverley",
	"C_Leader_Natural_King",
	"C_Leader_Natural_President",
	"C_Leader_Navy_Buff",
	"C_Leader_Philistine",
	"C_Leader_Uncouth",
	"C_Leader_Witty",
	"C_Minister_Army_Good",
	"C_Minister_Corrupt",
	"C_Minister_Entertainer",
	"C_Minister_Fiscal_Genius",
	"C_Minister_Industrialist",
	"C_Minister_Miser",
	"C_Minister_Navy_Good",
	"C_Minister_Physiocrat",
	"C_Minister_Radical",
	"C_Minister_Reactionary",
	"C_Minister_Trader",
	"C_Minister_Unjust",
	"C_Minister_Upright",
	"C_Missionary_Gone_Native",
	"C_Missionary_Gone_Native",
	"C_Missionary_Gone_Native",
	"C_Missionary_Gone_Native",
	"C_Missionary_Gone_Native",
	"C_Missionary_Hate_America",
	"C_Missionary_Hate_America",
	"C_Missionary_Hate_America",
	"C_Missionary_Hate_America",
	"C_Missionary_Hate_America",
	"C_Missionary_Hate_Europe",
	"C_Missionary_Hate_Europe",
	"C_Missionary_Hate_Europe",
	"C_Missionary_Hate_Europe",
	"C_Missionary_Hate_Europe",
	"C_Missionary_Hate_India",
	"C_Missionary_Hate_India",
	"C_Missionary_Hate_India",
	"C_Missionary_Hate_India",
	"C_Missionary_Hate_India",
	"C_Missionary_Like_America",
	"C_Missionary_Like_America",
	"C_Missionary_Like_America",
	"C_Missionary_Like_America",
	"C_Missionary_Like_America",
	"C_Missionary_Like_Europe",
	"C_Missionary_Like_Europe",
	"C_Missionary_Like_Europe",
	"C_Missionary_Like_Europe",
	"C_Missionary_Like_Europe",
	"C_Missionary_Like_India",
	"C_Missionary_Like_India",
	"C_Missionary_Like_India",
	"C_Missionary_Like_India",
	"C_Missionary_Like_India",
	"C_Missionary_Touched_By_God",
	"C_Missionary_Touched_By_God",
	"C_Missionary_Touched_By_God",
	"C_Missionary_Touched_By_God",
	"C_Missionary_Touched_By_God",
	"C_Personal_Hale",
	"C_Personal_Hale",
	"C_Personal_Hale",
	"C_Personal_Hale",
	"C_Personal_Hale",
	"C_Personal_Hale",
	"C_Personal_Hale",
	"C_Personal_Hale",
	"C_Personal_Hale",
	"C_Personal_Hale",
	"C_Personal_Hale",
	"C_Personal_High_Personal_Security",
	"C_Personal_High_Personal_Security",
	"C_Personal_High_Personal_Security",
	"C_Personal_High_Personal_Security",
	"C_Personal_High_Personal_Security",
	"C_Personal_Piety",
	"C_Personal_Piety",
	"C_Personal_Piety",
	"C_Personal_Piety",
	"C_Personal_Sickly",
	"C_Personal_Sickly",
	"C_Personal_Sickly",
	"C_Personal_Sickly",
	"C_Personal_Sickly",
	"C_Personal_Sickly",
	"C_Personal_Sickly",
	"C_Personal_Sickly",
	"C_Personal_Sickly",
	"C_Personal_Sickly",
	"C_Personal_Sickly",
	"C_Rake_Assassin_Good",
	"C_Rake_Assassin_Good",
	"C_Rake_Born_Bounder",
	"C_Rake_Born_Bounder",
	"C_Rake_Counter_Spy",
	"C_Rake_Counter_Spy",
	"C_Rake_Gate_Opener",
	"C_Rake_Gate_Opener",
	"C_Rake_Im_A_Laydee",
	"C_Rake_Naughty_Club",
	"C_Rake_Sabot_Good",
	"C_Rake_Sabot_Good",
	"C_Rake_Spy_Good",
	"C_Rake_Spy_Good",
	"C_Sausage_Vice",
	"C_Sausage_Vice",
	"C_Siege_Engineering",
	"C_Tribal_General_Attacker_Bad",
	"C_Tribal_General_Attacker_Good",
	"C_Tribal_General_Bad_Field_Commander",
	"C_Tribal_General_Bloody",
	"C_Tribal_General_Born_Soldier",
	"C_Tribal_General_Brave",
	"C_Tribal_General_Cherokee",
	"C_Tribal_General_Coward",
	"C_Tribal_General_Defender_Bad",
	"C_Tribal_General_Defender_Good",
	"C_Tribal_General_Good_Field_Commander",
	"C_Tribal_General_Hates_Europeans",
	"C_Tribal_General_Hates_Europeans_Reset",
	"C_Tribal_General_Huron",
	"C_Tribal_General_Iroquois",
	"C_Tribal_General_Lampooned",
	"C_Tribal_General_Mad",
	"C_Tribal_General_of_Cavalry",
	"C_Tribal_General_Plains",
	"C_Tribal_General_Plains_Coup",
	"C_Tribal_General_Press_Hero",
	"C_Tribal_General_Pueblo",
	"C_Tribal_General_Siege_Attack_Bad",
	"C_Tribal_General_Siege_Attack_Good",
	"C_Tribal_General_Siege_Defend_Bad",
	"C_Tribal_General_Siege_Defend_Good",
	"C_Tribal_Leader_Catholic",
	"C_Tribal_Leader_Clever_Stick",
	"C_Tribal_Leader_Cursed_Iroquois_Flying_Head",
	"C_Tribal_Leader_Debauched",
	"C_Tribal_Leader_Dullard",
	"C_Tribal_Leader_Foreign_Tastes",
	"C_Tribal_Leader_Harsh_Ruler",
	"C_Tribal_Leader_Hindu",
	"C_Tribal_Leader_Huntin_Shootin_Fishin",
	"C_Tribal_Leader_Islamic",
	"C_Tribal_Leader_Mad",
	"C_Tribal_Leader_Orthodox",
	"C_Tribal_Leader_Peacemaker",
	"C_Tribal_Leader_Plains_Cursed",
	"C_Tribal_Leader_Protestant",
	"C_Tribal_Minister_Agriculturalist",
	"C_Tribal_Minister_Army_Good",
	"C_Tribal_Minister_Industrialist",
	"C_Tribal_Minister_Trader",
	"C_Tribal_Scout_Good_Army_Sabotage",
	"C_Tribal_Scout_Good_Assassin",
	"C_Tribal_Scout_Good_Spy",
	"C_Tribal_Scout_Sabot_Good",
	"C_Tribal_Shaman_Likes_Mushrooms",
	"C_Tribal_Shaman_Plains_Buffalo_Dancer",
	"C_Tribal_Shaman_Powwow",
	"C_Tribal_Shaman_Pueblo_Sun_Dancer",
	"C_Tribal_Shaman_Research_Military",
}


-- list of all slot ids
slotsList = {
  ["caribbean:bahamas:andros"] = "bahamas",
  ["caribbean:cuba:central"] = "cuba",
  ["caribbean:curacao:aruba"] = "curacao",
  ["caribbean:florida:south"] = "florida",
  ["caribbean:guatemala:honduras"] = "guatemala",
  ["caribbean:hispaniola:central"] = "hispaniola",
  ["caribbean:hispaniola:east"] = "hispaniola",
  ["caribbean:jamaica:west"] = "jamaica",
  ["caribbean:leeward_islands:dominica"] = "leeward_islands",
  ["caribbean:lower_louisiana:coast"] = "lower_louisiana",
  ["caribbean:new_andalusia:barinas"] = "new_andalusia",
  ["caribbean:new_spain:veracruz"] = "new_spain",
  ["caribbean:panama:costa_rica"] = "panama",
  ["caribbean:panama:south-central"] = "panama",
  ["caribbean:trinidad_tobago:south"] = "trinidad_tobago",
  ["caribbean:windward_islands:st_vincent"] = "windward_islands",
  ["corn:acadia:nova_scotia"] = "acadia",
  ["corn:algonquin_territory:lake"] = "algonquin_territory",
  ["corn:carolinas:coast"] = "carolinas",
  ["corn:carolinas:east"] = "carolinas",
  ["corn:cherokee_territory:north"] = "cherokee_territory",
  ["corn:cuba:west"] = "cuba",
  ["corn:florida:north"] = "florida",
  ["corn:great_plains:central"] = "great_plains",
  ["corn:guatemala:west"] = "guatemala",
  ["corn:hispaniola:west"] = "hispaniola",
  ["corn:iroquois_territory:lake"] = "iroquois_territory",
  ["corn:kaintuck_territory:north"] = "kaintuck_territory",
  ["corn:lower_louisiana:river"] = "lower_louisiana",
  ["corn:michigan_territory:north"] = "michigan_territory",
  ["corn:michigan_territory:south"] = "michigan_territory",
  ["corn:new_andalusia:coast"] = "new_andalusia",
  ["corn:new_england:cape_cod"] = "new_england",
  ["corn:new_france:south_river"] = "new_france",
  ["corn:new_grenada:tunja"] = "new_grenada",
  ["corn:new_spain:monterey"] = "new_spain",
  ["corn:new_spain:south_central"] = "new_spain",
  ["corn:new_york:long_island"] = "new_york",
  ["corn:ontario:south"] = "ontario",
  ["corn:ruperts_land:south"] = "ruperts_land",
  ["corn:tejas:south"] = "tejas",
  ["corn:upper_louisiana:south"] = "upper_louisiana",
  ["corn:virginia:north"] = "virginia",
  ["cuba:cuba:central"] = "cuba",
  ["cuba:cuba:havana"] = "cuba",
  ["cuba:hispaniola:haiti"] = "cuba",
  ["egypt:egypt:luxor"] = "egypt",
  ["egypt:mesopotamia:kirkuk"] = "mesopotamia",
  ["egypt:syria:north"] = "syria",
  ["fur:algonquin_territory:almostisland"] = "algonquin_territory",
  ["fur:arkhangelsk:central"] = "arkhangelsk",
  ["fur:arkhangelsk:far_north"] = "arkhangelsk",
  ["fur:bashkira:urals"] = "bashkira",
  ["fur:finland:east"] = "finland",
  ["fur:georgia:dusheti"] = "georgia",
  ["fur:great_plains:lake_manitoba"] = "great_plains",
  ["fur:huron_territory:north"] = "huron_territory",
  ["fur:iroquois_territory:st_lawrence"] = "iroquois_territory",
  ["fur:karelia:south"] = "karelia",
  ["fur:labrador:coastcentral"] = "labrador",
  ["fur:new_england:south"] = "new_england",
  ["fur:new_france:central"] = "new_france",
  ["fur:new_york:north"] = "new_york",
  ["fur:newfoundland:central"] = "newfoundland",
  ["fur:northwest_territories:east"] = "northwest_territories",
  ["fur:ontario:ottawa_r"] = "ontario",
  ["fur:ruperts_land:albany_river"] = "ruperts_land",
  ["fur:ruperts_land:east"] = "ruperts_land",
  ["fur:sweden:east"] = "sweden",
  ["fur:tatariya:kazan"] = "tatariya",
  ["gems:carnatica:south"] = "carnatica",
  ["gems:ceylon:central"] = "ceylon",
  ["gems:dutch_guyana:west"] = "dutch_guyana",
  ["gems:mysore:east"] = "mysore",
  ["gems:new_andalusia:el_dorado"] = "new_andalusia",
  ["gold:austria:rauris"] = "austria",
  ["gold:dutch_guyana:central"] = "dutch_guyana",
  ["gold:french_guyana:south"] = "french_guyana",
  ["gold:huron_territory:west"] = "huron_territory",
  ["gold:mysore:bangalore"] = "mysore",
  ["gold:new_grenada:medellin"] = "new_grenada",
  ["gold:new_grenada:south"] = "new_grenada",
  ["gold:new_spain:west"] = "new_spain",
  ["gold:punjab:central"] = "punjab",
  ["india_highlands:ahmadnagar:centraleast"] = "ahmadnagar",
  ["india_highlands:bengal:northeast"] = "bengal",
  ["india_highlands:berar:southwest"] = "berar",
  ["india_highlands:bijapur:east"] = "bijapur",
  ["india_highlands:carnatica:south"] = "carnatica",
  ["india_highlands:ceylon:southwest"] = "ceylon",
  ["india_highlands:gujarat:southeast"] = "gujarat",
  ["india_highlands:hindustan:north"] = "hindustan",
  ["india_highlands:hyderabad:north"] = "hyderabad",
  ["india_highlands:malabar:east"] = "malabar",
  ["india_highlands:malwa:west"] = "malwa",
  ["india_highlands:mysore:central"] = "mysore",
  ["india_highlands:rajpootana:west"] = "rajpootana",
  ["iron:algiers:zaccar"] = "algiers",
  ["iron:alsace:metz"] = "alsace",
  ["iron:anatolia:denizli"] = "anatolia",
  ["iron:armenia:oltu"] = "armenia",
  ["iron:austria:central"] = "austria",
  ["iron:bavaria:east"] = "bavaria",
  ["iron:berar:east"] = "berar",
  ["iron:bohemia:ostrau"] = "bohemia",
  ["iron:bosnia:sarajevo"] = "bosnia",
  ["iron:bulgaria:southwest"] = "bulgaria",
  ["iron:cherokee_territory:northeast"] = "cherokee_territory",
  ["iron:crimea:rog"] = "crimea",
  ["iron:england:near_birmingham"] = "england",
  ["iron:finland:central"] = "finland",
  ["iron:france:massifcentral"] = "france",
  ["iron:karelia:north"] = "karelia",
  ["iron:maine:north"] = "maine",
  ["iron:moldavia:carpatians"] = "moldavia",
  ["iron:morocco:imini"] = "morocco",
  ["iron:muscovy:bryansk"] = "muscovy",
  ["iron:new_france:south"] = "new_france",
  ["iron:new_york:north"] = "new_york",
  ["iron:norway:mo_i_randa"] = "norway",
  ["iron:norway:north"] = "norway",
  ["iron:orissa:north"] = "orissa",
  ["iron:pennsylvania:west"] = "pennsylvania",
  ["iron:persia:bafq"] = "persia",
  ["iron:punjab:west"] = "punjab",
  ["iron:rajpootana:south"] = "rajpootana",
  ["iron:rhineland:eisenach"] = "rhineland",
  ["iron:saxony:south"] = "saxony",
  ["iron:spain:cantabria"] = "spain",
  ["iron:sweden:fagersta"] = "sweden",
  ["iron:syria:cyprus"] = "syria",
  ["iron:tatariya:donezk"] = "tatariya",
  ["iron:transylvania:south"] = "transylvania",
  ["iron:tunis:djerissa"] = "tunis",
  ["iron:ukraine:belgorod"] = "ukraine",
  ["rice:ahmadnagar:coastnorth"] = "ahmadnagar",
  ["rice:bengal:centralnorth"] = "bengal",
  ["rice:bengal:northwest"] = "bengal",
  ["rice:berar:raipur"] = "berar",
  ["rice:bijapur:coastnorth"] = "bijapur",
  ["rice:carnatica:coastnorth"] = "carnatica",
  ["rice:ceylon:northwest"] = "ceylon",
  ["rice:hindustan:agra"] = "hindustan",
  ["rice:hindustan:east"] = "hindustan",
  ["rice:hyderabad:centralnorth"] = "hyderabad",
  ["rice:mysore:coastsouth"] = "mysore",
  ["rice:orissa:coastsouth"] = "orissa",
  ["rice:orissa:east"] = "orissa",
  ["rice:punjab:central2"] = "punjab",
  ["rice:sindh:south"] = "sindh",
  ["sheep:afghanistan:north"] = "afghanistan",
  ["sheep:afghanistan:southeast"] = "afghanistan",
  ["sheep:algiers:tizi-ouzou"] = "algiers",
  ["sheep:anatolia:central_north"] = "anatolia",
  ["sheep:armenia:agri"] = "armenia",
  ["sheep:austria:tyrol"] = "austria",
  ["sheep:azerbaijan:senjan"] = "azerbaijan",
  ["sheep:baluchistan:south"] = "baluchistan",
  ["sheep:bashkira:orenburg"] = "bashkira",
  ["sheep:belarus:west"] = "belarus",
  ["sheep:bohemia:brunn"] = "bohemia",
  ["sheep:bulgaria:central"] = "bulgaria",
  ["sheep:chechenya-dagestan:inland"] = "chechenya-dagestan",
  ["sheep:croatia:zagreb"] = "croatia",
  ["sheep:denmark:north"] = "denmark",
  ["sheep:don_voisko:krasnodar"] = "don_voisko",
  ["sheep:england:cornwall"] = "england",
  ["sheep:flanders:east"] = "flanders",
  ["sheep:france:bretagne"] = "france",
  ["sheep:georgia:mingrelia"] = "georgia",
  ["sheep:greece:west"] = "greece",
  ["sheep:hungary:balaton"] = "hungary",
  ["sheep:iceland:skogar"] = "iceland",
  ["sheep:ireland:dublin"] = "ireland",
  ["sheep:kashmir:east"] = "kashmir",
  ["sheep:kashmir:jammu"] = "kashmir",
  ["sheep:morea:southeast"] = "morea",
  ["sheep:morocco:meknes"] = "morocco",
  ["sheep:muscovy:velikiye_luki"] = "muscovy",
  ["sheep:naples:foggia"] = "naples",
  ["sheep:netherlands:south"] = "netherlands",
  ["sheep:new_england:north"] = "new_england",
  ["sheep:norway:south"] = "norway",
  ["sheep:pennsylvania:scranton"] = "pennsylvania",
  ["sheep:persia:yazd"] = "persia",
  ["sheep:poland:lodz"] = "poland",
  ["sheep:portugal:alto_alentejo"] = "portugal",
  ["sheep:rumelia:kavala"] = "rumelia",
  ["sheep:scotland:highlands_east"] = "scotland",
  ["sheep:serbia:central"] = "serbia",
  ["sheep:tatariya:rasskasovo"] = "tatariya",
  ["sheep:west_pommerania:berlin"] = "west_pommerania",
  ["silver:acadia:central"] = "acadia",
  ["silver:guatemala:central"] = "guatemala",
  ["silver:new_grenada:medellin"] = "new_grenada",
  ["silver:new_spain:central_east"] = "new_spain",
  ["silver:new_spain:northwest"] = "new_spain",
  ["silver:sardinia:iglesias"] = "sardinia",
  ["silver:serbia:south"] = "serbia",
  ["silver:sweden:kristineberg"] = "sweden",
  ["southern_usa:carolinas:coast"] = "carolinas",
  ["southern_usa:cherokee_territory:south"] = "cherokee_territory",
  ["southern_usa:florida:north"] = "florida",
  ["southern_usa:georgia_usa:central"] = "georgia_usa",
  ["southern_usa:kaintuck_territory:central"] = "kaintuck_territory",
  ["southern_usa:lower_louisiana:riversouth"] = "lower_louisiana",
  ["southern_usa:new_mexico:south"] = "new_mexico",
  ["southern_usa:new_spain:rio_grande"] = "new_spain",
  ["southern_usa:tejas:west"] = "tejas",
  ["southern_usa:upper_louisiana:ohio"] = "upper_louisiana",
  ["southern_usa:virginia:central"] = "virginia",
  ["southern_usa:virginia:north"] = "virginia",
  ["timber:arkhangelsk:south_central"] = "arkhangelsk",
  ["timber:arkhangelsk:west"] = "arkhangelsk",
  ["timber:courland:central"] = "courland",
  ["timber:dutch_guyana:east"] = "dutch_guyana",
  ["timber:finland:oulu"] = "finland",
  ["timber:galicia:carpatians"] = "galicia",
  ["timber:ingria:st_petersburg"] = "ingria",
  ["timber:karelia:east"] = "karelia",
  ["timber:muscovy:borovichi"] = "muscovy",
  ["timber:new_france:east"] = "new_france",
  ["timber:newfoundland:north"] = "newfoundland",
  ["timber:norway:oslo"] = "norway",
  ["timber:norway:trondheim"] = "norway",
  ["timber:sweden:karlstad"] = "sweden",
  ["timber:sweden:sundsvall"] = "sweden",
  ["tropical_humid:bengal:southeast"] = "bengal",
  ["tropical_humid:carnatica:south"] = "carnatica",
  ["tropical_humid:dutch_guyana:coast"] = "dutch_guyana",
  ["tropical_humid:french_guyana:north"] = "french_guyana",
  ["tropical_humid:hindustan:central"] = "hindustan",
  ["wheat:anatolia:adana"] = "anatolia",
  ["wheat:astrakhan:volga"] = "astrakhan",
  ["wheat:austria:north"] = "austria",
  ["wheat:azerbaijan:salyan"] = "azerbaijan",
  ["wheat:bashkira:togliatti"] = "bashkira",
  ["wheat:belarus:centraleast"] = "belarus",
  ["wheat:bosnia:northwest"] = "bosnia",
  ["wheat:bulgaria:sofia"] = "bulgaria",
  ["wheat:courland:east"] = "courland",
  ["wheat:crimea:bratslav"] = "crimea",
  ["wheat:crimea:volga_mouth"] = "crimea",
  ["wheat:denmark:south"] = "denmark",
  ["wheat:don_voisko:kanev"] = "don_voisko",
  ["wheat:egypt:delta"] = "egypt",
  ["wheat:england:east_anglia"] = "england",
  ["wheat:england:hull"] = "england",
  ["wheat:estonia_and_livonia:south"] = "estonia_and_livonia",
  ["wheat:france:loire"] = "france",
  ["wheat:galicia:east"] = "galicia",
  ["wheat:gujarat:south"] = "gujarat",
  ["wheat:hindustan:west"] = "hindustan",
  ["wheat:hungary:central"] = "hungary",
  ["wheat:hyderabad:central"] = "hyderabad",
  ["wheat:ingria:central"] = "ingria",
  ["wheat:lithuania:daugpils"] = "lithuania",
  ["wheat:lithuania:kaunas"] = "lithuania",
  ["wheat:malwa:north"] = "malwa",
  ["wheat:mesopotamia:baghdad"] = "mesopotamia",
  ["wheat:moldavia:southeast"] = "moldavia",
  ["wheat:morocco:guercif"] = "morocco",
  ["wheat:muscovy:saransk"] = "muscovy",
  ["wheat:muscovy:tula"] = "muscovy",
  ["wheat:naples:ragusa"] = "naples",
  ["wheat:netherlands:north"] = "netherlands",
  ["wheat:newfoundland:coastsouth"] = "newfoundland",
  ["wheat:persia:south"] = "persia",
  ["wheat:poland:cracow"] = "poland",
  ["wheat:prussia:southwest"] = "prussia",
  ["wheat:punjab:south"] = "punjab",
  ["wheat:rajpootana:north"] = "rajpootana",
  ["wheat:rhineland:north"] = "rhineland",
  ["wheat:rumelia:north"] = "rumelia",
  ["wheat:saxony:erfurt"] = "saxony",
  ["wheat:silesia:south"] = "silesia",
  ["wheat:sindh:central"] = "sindh",
  ["wheat:spain:ebro"] = "spain",
  ["wheat:spain:seville"] = "spain",
  ["wheat:sweden:vanersee"] = "sweden",
  ["wheat:tatariya:pensa"] = "tatariya",
  ["wheat:transylvania:central"] = "transylvania",
  ["wheat:tunis:coast"] = "tunis",
  ["wheat:ukraine:kiev"] = "ukraine",
  ["wheat:ukraine:poltava"] = "ukraine",
  ["wheat:west_pommerania:rostock"] = "west_pommerania",
  ["wheat:west_prussia:southeast"] = "west_prussia",
  ["wine:anatolia:west"] = "anatolia",
  ["wine:corsica:east"] = "corsica",
  ["wine:croatia:west"] = "croatia",
  ["wine:france:bordeaux"] = "france",
  ["wine:france:loire_valley"] = "france",
  ["wine:genoa:la_spezia"] = "genoa",
  ["wine:greece:athens"] = "greece",
  ["wine:greece:central"] = "greece",
  ["wine:morea:patras"] = "morea",
  ["wine:naples:calabria"] = "naples",
  ["wine:naples:west_sicily"] = "naples",
  ["wine:portugal:porto"] = "portugal",
  ["wine:rumelia:central"] = "rumelia",
  ["wine:sardinia:east"] = "sardinia",
  ["wine:savoy:niece"] = "savoy",
  ["wine:spain:central"] = "spain",
  ["wine:the_papal_states:florence"] = "the_papal_states",
  ["wine:the_papal_states:rome"] = "the_papal_states",
  ["wine:the_papal_states:san_marino"] = "the_papal_states",
  ["wine:venice:udine"] = "venice",
  ["wine:wurttemberg:freiburg"] = "wurttemberg",
  ["port:acadia:cap_fourchu"] = "acadia",
  ["port:acadia:louisbourg"] = "acadia",
  ["port:ahmadnagar:bombay"] = "ahmadnagar",
  ["port:algiers:annaba"] = "algiers",
  ["port:algiers:oran"] = "algiers",
  ["port:anatolia:antalya"] = "anatolia",
  ["port:anatolia:izmir"] = "anatolia",
  ["port:anatolia:sinop"] = "anatolia",
  ["port:austria:triest"] = "austria",
  ["port:bahamas:grand_bahama"] = "bahamas",
  ["port:bengal:port_of_calcutta"] = "bengal",
  ["port:bosnia:ragusa"] = "bosnia",
  ["port:bulgaria:burgas"] = "bulgaria",
  ["port:bulgaria:varna"] = "bulgaria",
  ["port:carnatica:calicut"] = "carnatica",
  ["port:carnatica:madras"] = "carnatica",
  ["port:carnatica:pondicherry"] = "carnatica",
  ["port:carolinas:georgetown"] = "carolinas",
  ["port:ceylon:colombo"] = "ceylon",
  ["port:corsica:ajaccio"] = "corsica",
  ["port:courland:liepaja"] = "courland",
  ["port:crimea:odessa"] = "crimea",
  ["port:crimea:sevastopol"] = "crimea",
  ["port:croatia:rijeka"] = "croatia",
  ["port:croatia:zadar"] = "croatia",
  ["port:cuba:holguin"] = "cuba",
  ["port:cuba:santiago_de_cuba"] = "cuba",
  ["port:curacao:otrobanda"] = "curacao",
  ["port:denmark:aarhus"] = "denmark",
  ["port:denmark:husum"] = "denmark",
  ["port:denmark:lubeck"] = "denmark",
  ["port:dutch_guyana:demerara"] = "dutch_guyana",
  ["port:egypt:alexandria"] = "egypt",
  ["port:england:bristol"] = "england",
  ["port:england:liverpool"] = "england",
  ["port:england:london"] = "england",
  ["port:england:newcastle"] = "england",
  ["port:england:portsmouth"] = "england",
  ["port:estonia_and_livonia:parnu"] = "estonia_and_livonia",
  ["port:finland:helsingfors"] = "finland",
  ["port:flanders:antwerp"] = "flanders",
  ["port:florida:pensacola"] = "florida",
  ["port:france:brest"] = "france",
  ["port:france:calais"] = "france",
  ["port:france:le_havre"] = "france",
  ["port:france:marseille"] = "france",
  ["port:french_guyana:sinnamary"] = "french_guyana",
  ["port:genoa:imperia"] = "genoa",
  ["port:georgia:batomi"] = "georgia",
  ["port:georgia_usa:st_marys"] = "georgia_usa",
  ["port:gibraltar:sandy_bay"] = "gibraltar",
  ["port:greece:heraklion"] = "greece",
  ["port:greece:piraeus"] = "greece",
  ["port:guatemala:puerto_barrios"] = "guatemala",
  ["port:gujarat:porbandar"] = "gujarat",
  ["port:gujarat:surat"] = "gujarat",
  ["port:hannover:cuxhaven"] = "hannover",
  ["port:hispaniola:leogane"] = "hispaniola",
  ["port:hispaniola:port-de-paix"] = "hispaniola",
  ["port:hispaniola:san_juan"] = "hispaniola",
  ["port:iceland:akureyri"] = "iceland",
  ["port:iceland:hofn"] = "iceland",
  ["port:ingria:kronstadt"] = "ingria",
  ["port:ingria:staraya_ladoga"] = "ingria",
  ["port:ireland:belfast"] = "ireland",
  ["port:ireland:waterford"] = "ireland",
  ["port:jamaica:kingston"] = "jamaica",
  ["port:karelia:severomorsk"] = "karelia",
  ["port:labrador:cartwright"] = "labrador",
  ["port:labrador:catucto"] = "labrador",
  ["port:leeward_islands:guadeloupe"] = "leeward_islands",
  ["port:lower_louisiana:mobile"] = "lower_louisiana",
  ["port:maine:eastport"] = "maine",
  ["port:malabar:barcelor"] = "malabar",
  ["port:malta:marsaxlokk"] = "malta",
  ["port:mesopotamia:basra"] = "mesopotamia",
  ["port:morea:pylos"] = "morea",
  ["port:morocco:agadir"] = "morocco",
  ["port:morocco:casabranca"] = "morocco",
  ["port:mysore:mangalore"] = "mysore",
  ["port:naples:siracusa"] = "naples",
  ["port:naples:taranto"] = "naples",
  ["port:netherlands:rotterdam"] = "netherlands",
  ["port:new_andalusia:coro"] = "new_andalusia",
  ["port:new_andalusia:puerto_cabello"] = "new_andalusia",
  ["port:new_england:plymouth"] = "new_england",
  ["port:new_england:providence"] = "new_england",
  ["port:new_france:tadoussac"] = "new_france",
  ["port:new_grenada:cartagena"] = "new_grenada",
  ["port:new_grenada:rio_de_la_hacha"] = "new_grenada",
  ["port:new_spain:campeche"] = "new_spain",
  ["port:new_spain:tampico"] = "new_spain",
  ["port:new_spain:veracruz"] = "new_spain",
  ["port:new_york:new_york"] = "new_york",
  ["port:newfoundland:st_johns"] = "newfoundland",
  ["port:northwest_territories:churchill"] = "northwest_territories",
  ["port:norway:bergen"] = "norway",
  ["port:orissa:puri"] = "orissa",
  ["port:orissa:yanaon"] = "orissa",
  ["port:palestine:gaza"] = "palestine",
  ["port:panama:puerto_bello"] = "panama",
  ["port:pennsylvania:lewes"] = "pennsylvania",
  ["port:persia:bandar_abbas"] = "persia",
  ["port:portugal:porto"] = "portugal",
  ["port:prussia:memel"] = "prussia",
  ["port:rumelia:thessaloniki"] = "rumelia",
  ["port:ruperts_land:fort_albany"] = "ruperts_land",
  ["port:sardinia:alghero"] = "sardinia",
  ["port:savoy:niece"] = "savoy",
  ["port:scotland:glasgow"] = "scotland",
  ["port:sindh:kolachi"] = "sindh",
  ["port:spain:bilbao"] = "spain",
  ["port:spain:cadiz"] = "spain",
  ["port:spain:cartagena"] = "spain",
  ["port:spain:palma_de_mallorca"] = "spain",
  ["port:sweden:malmo"] = "sweden",
  ["port:sweden:umeaa"] = "sweden",
  ["port:sweden:visby"] = "sweden",
  ["port:syria:beirut"] = "syria",
  ["port:syria:latakia"] = "syria",
  ["port:syria:limassol"] = "syria",
  ["port:tejas:corpus_christi"] = "tejas",
  ["port:the_papal_states:ravenna"] = "the_papal_states",
  ["port:trinidad_tobago:puerto_de_espana"] = "trinidad_tobago",
  ["port:tripoli:surt"] = "tripoli",
  ["port:tunis:safaqis"] = "tunis",
  ["port:venice:chioggia"] = "venice",
  ["port:virginia:yorktown"] = "virginia",
  ["port:west_pommerania:rostock"] = "west_pommerania",
  ["port:west_prussia:gdynia"] = "west_prussia",
  ["port:windward_islands:barbados"] = "windward_islands",
  ["town:acadia:bathurst"] = "acadia",
  ["town:acadia:fort_nashwaak_ep3"] = "acadia",
  ["town:afghanistan:herat"] = "afghanistan",
  ["town:afghanistan:kandahar"] = "afghanistan",
  ["town:afghanistan:mazari_sharif"] = "afghanistan",
  ["town:ahmadnagar:pune"] = "ahmadnagar",
  ["town:algiers:bejaia"] = "algiers",
  ["town:algonquin_territory:fort_duquesne"] = "algonquin_territory",
  ["town:algonquin_territory:fort_presque_isle"] = "algonquin_territory",
  ["town:alsace:nancy"] = "alsace",
  ["town:anatolia:batman"] = "anatolia",
  ["town:anatolia:bursa"] = "anatolia",
  ["town:anatolia:erzurum"] = "anatolia",
  ["town:anatolia:kayseri"] = "anatolia",
  ["town:anatolia:konya"] = "anatolia",
  ["town:anatolia:trabzon"] = "anatolia",
  ["town:armenia:artvin"] = "armenia",
  ["town:armenia:kars"] = "armenia",
  ["town:astrakhan:samara"] = "astrakhan",
  ["town:austria:graz"] = "austria",
  ["town:austria:innsbruck"] = "austria",
  ["town:austria:salzburg"] = "austria",
  ["town:azerbaijan:baku"] = "azerbaijan",
  ["town:azerbaijan:ganja"] = "azerbaijan",
  ["town:azerbaijan:rasht"] = "azerbaijan",
  ["town:azerbaijan:tabriz"] = "azerbaijan",
  ["town:baluchistan:khuzdar"] = "baluchistan",
  ["town:baluchistan:turbat"] = "baluchistan",
  ["town:bashkira:orenburg"] = "bashkira",
  ["town:bavaria:augsburg"] = "bavaria",
  ["town:bavaria:coburg"] = "bavaria",
  ["town:bavaria:nurnberg"] = "bavaria",
  ["town:belarus:babruysk"] = "belarus",
  ["town:belarus:homyel"] = "belarus",
  ["town:belarus:pinsk"] = "belarus",
  ["town:belarus:vitebsk"] = "belarus",
  ["town:bengal:bhagalpur"] = "bengal",
  ["town:bengal:dacca"] = "bengal",
  ["town:bengal:patna"] = "bengal",
  ["town:berar:chanda"] = "berar",
  ["town:berar:raipur"] = "berar",
  ["town:bijapur:bijapur"] = "bijapur",
  ["town:bijapur:kolhapur"] = "bijapur",
  ["town:bohemia:budweis"] = "bohemia",
  ["town:bohemia:olmutz"] = "bohemia",
  ["town:bosnia:bijeljina"] = "bosnia",
  ["town:bosnia:podgorica"] = "bosnia",
  ["town:bulgaria:bucharest"] = "bulgaria",
  ["town:bulgaria:craiova"] = "bulgaria",
  ["town:carnatica:cochin"] = "carnatica",
  ["town:carnatica:trichinopoly"] = "carnatica",
  ["town:carolinas:charlotte"] = "carolinas",
  ["town:carolinas:raleigh"] = "carolinas",
  ["town:ceylon:kandy"] = "ceylon",
  ["town:chechenya-dagestan:derbent"] = "chechenya-dagestan",
  ["town:cherokee_territory:autiamique"] = "cherokee_territory",
  ["town:cherokee_territory:casseta"] = "cherokee_territory",
  ["town:cherokee_territory:tuckabatchee"] = "cherokee_territory",
  ["town:courland:kuldiga"] = "courland",
  ["town:courland:ogre"] = "courland",
  ["town:crimea:czerkasy"] = "crimea",
  ["town:crimea:kerch"] = "crimea",
  ["town:croatia:osijek"] = "croatia",
  ["town:croatia:split"] = "croatia",
  ["town:cuba:puerto_principe"] = "cuba",
  ["town:curacao:kralendijk"] = "curacao",
  ["town:denmark:aalborg"] = "denmark",
  ["town:denmark:odense"] = "denmark",
  ["town:denmark:schleswig"] = "denmark",
  ["town:don_voisko:maikop"] = "don_voisko",
  ["town:don_voisko:stavropol"] = "don_voisko",
  ["town:egypt:aswan"] = "egypt",
  ["town:egypt:asyut"] = "egypt",
  ["town:egypt:darnah"] = "egypt",
  ["town:egypt:luxor"] = "egypt",
  ["town:egypt:suez"] = "egypt",
  ["town:england:birmingham"] = "england",
  ["town:england:cambridge"] = "england",
  ["town:england:manchester"] = "england",
  ["town:england:oxford"] = "england",
  ["town:england:swansea"] = "england",
  ["town:england:york"] = "england",
  ["town:estonia_and_livonia:narva"] = "estonia_and_livonia",
  ["town:estonia_and_livonia:tallinn"] = "estonia_and_livonia",
  ["town:finland:uleaborg"] = "finland",
  ["town:finland:vasa"] = "finland",
  ["town:flanders:ghent"] = "flanders",
  ["town:flanders:luxemburg"] = "flanders",
  ["town:florida:st_marks"] = "florida",
  ["town:florida:tequesta_mission"] = "florida",
  ["town:france:bordeaux"] = "france",
  ["town:france:clermont-ferrand"] = "france",
  ["town:france:dijon"] = "france",
  ["town:france:lille"] = "france",
  ["town:france:lyons"] = "france",
  ["town:france:nantes"] = "france",
  ["town:france:orleans"] = "france",
  ["town:france:toulouse"] = "france",
  ["town:galicia:brody"] = "galicia",
  ["town:galicia:kaminiec"] = "galicia",
  ["town:galicia:latyczov"] = "galicia",
  ["town:galicia:rzeszow"] = "galicia",
  ["town:genoa:la_spezia"] = "genoa",
  ["town:georgia:suhumkale"] = "georgia",
  ["town:great_plains:quivira"] = "great_plains",
  ["town:greece:ioannia"] = "greece",
  ["town:greece:larissa"] = "greece",
  ["town:guatemala:comayagua"] = "guatemala",
  ["town:guatemala:gran_granada"] = "guatemala",
  ["town:gujarat:baroda"] = "gujarat",
  ["town:hannover:braunschweig"] = "hannover",
  ["town:hannover:hamburg"] = "hannover",
  ["town:hindustan:benares"] = "hindustan",
  ["town:hindustan:delhi"] = "hindustan",
  ["town:hindustan:faizabad"] = "hindustan",
  ["town:hindustan:gwalior"] = "hindustan",
  ["town:hindustan:sitapur"] = "hindustan",
  ["town:hispaniola:santiago_de_los_caballeros"] = "hispaniola",
  ["town:hungary:budapest"] = "hungary",
  ["town:hungary:nyiregyhaza"] = "hungary",
  ["town:hungary:pecs"] = "hungary",
  ["town:hungary:szeged"] = "hungary",
  ["town:huron_territory:kapuskasing"] = "huron_territory",
  ["town:huron_territory:longlac"] = "huron_territory",
  ["town:hyderabad:golconda"] = "hyderabad",
  ["town:hyderabad:kurnool"] = "hyderabad",
  ["town:hyderabad:nizamabad"] = "hyderabad",
  ["town:ingria:luga"] = "ingria",
  ["town:ireland:cork"] = "ireland",
  ["town:ireland:galway"] = "ireland",
  ["town:iroquois_territory:mohawk"] = "iroquois_territory",
  ["town:iroquois_territory:oneida"] = "iroquois_territory",
  ["town:kaintuck_territory:lexington"] = "kaintuck_territory",
  ["town:kaintuck_territory:sycamore_shoals"] = "kaintuck_territory",
  ["town:karelia:kem"] = "karelia",
  ["town:kashmir:jammu"] = "kashmir",
  ["town:komi:perm"] = "komi",
  ["town:labrador:rigolet"] = "labrador",
  ["town:lithuania:brest"] = "lithuania",
  ["town:lithuania:daugpilis"] = "lithuania",
  ["town:lithuania:gardinas"] = "lithuania",
  ["town:lithuania:kaunas"] = "lithuania",
  ["town:lower_louisiana:baton_rouge"] = "lower_louisiana",
  ["town:lower_louisiana:little_rock"] = "lower_louisiana",
  ["town:maine:brunswick"] = "maine",
  ["town:malwa:bhopal"] = "malwa",
  ["town:malwa:ellichpur"] = "malwa",
  ["town:maryland:baltimore"] = "maryland",
  ["town:mesopotamia:erbil"] = "mesopotamia",
  ["town:mesopotamia:kut"] = "mesopotamia",
  ["town:mesopotamia:mosul"] = "mesopotamia",
  ["town:mesopotamia:najaf"] = "mesopotamia",
  ["town:michigan_territory:fort_st_joseph"] = "michigan_territory",
  ["town:michigan_territory:kekionga"] = "michigan_territory",
  ["town:milan:cremona"] = "milan",
  ["town:moldavia:tighina"] = "moldavia",
  ["town:morea:corinth"] = "morea",
  ["town:morocco:fes"] = "morocco",
  ["town:morocco:marrakech"] = "morocco",
  ["town:muscovy:bryansk"] = "muscovy",
  ["town:muscovy:nizhny_novgorod"] = "muscovy",
  ["town:muscovy:pereslavl-ryazansky"] = "muscovy",
  ["town:muscovy:rybinsk"] = "muscovy",
  ["town:muscovy:smolensk"] = "muscovy",
  ["town:muscovy:velikiy_novgorod"] = "muscovy",
  ["town:muscovy:vishniy_volochek"] = "muscovy",
  ["town:muscovy:yaroslavl"] = "muscovy",
  ["town:mysore:bangalore"] = "mysore",
  ["town:mysore:bellary"] = "mysore",
  ["town:mysore:srirangapatna"] = "mysore",
  ["town:naples:l_aquila"] = "naples",
  ["town:naples:palermo"] = "naples",
  ["town:naples:potenza"] = "naples",
  ["town:netherlands:den_haag"] = "netherlands",
  ["town:netherlands:utrecht"] = "netherlands",
  ["town:new_andalusia:cumana"] = "new_andalusia",
  ["town:new_england:hartford"] = "new_england",
  ["town:new_england:new_haven"] = "new_england",
  ["town:new_france:gaspe"] = "new_france",
  ["town:new_france:trois_rivieres"] = "new_france",
  ["town:new_grenada:maracaibo"] = "new_grenada",
  ["town:new_grenada:medellin"] = "new_grenada",
  ["town:new_grenada:santiago_de_cali"] = "new_grenada",
  ["town:new_mexico:el_paso"] = "new_mexico",
  ["town:new_spain:guadalajara"] = "new_spain",
  ["town:new_spain:monterrey"] = "new_spain",
  ["town:new_spain:villahermosa"] = "new_spain",
  ["town:new_york:saratoga"] = "new_york",
  ["town:newfoundland:bonavista"] = "newfoundland",
  ["town:norway:stavanger"] = "norway",
  ["town:norway:trondheim"] = "norway",
  ["town:ontario:fort_frontenac"] = "ontario",
  ["town:ontario:sault_sainte-marie"] = "ontario",
  ["town:ontario:tkaronto"] = "ontario",
  ["town:orissa:masulipatnam"] = "orissa",
  ["town:orissa:sambalpur"] = "orissa",
  ["town:orissa:vizianagram"] = "orissa",
  ["town:palestine:elat"] = "palestine",
  ["town:panama:san_jose"] = "panama",
  ["town:pennsylvania:dover"] = "pennsylvania",
  ["town:pennsylvania:harrisburg"] = "pennsylvania",
  ["town:persia:kermanshah"] = "persia",
  ["town:persia:mashad"] = "persia",
  ["town:persia:qom"] = "persia",
  ["town:persia:shiraz"] = "persia",
  ["town:persia:teheran"] = "persia",
  ["town:persia:yazd"] = "persia",
  ["town:poland:bialystok"] = "poland",
  ["town:poland:cracow"] = "poland",
  ["town:poland:lodz"] = "poland",
  ["town:poland:lublin"] = "poland",
  ["town:portugal:covilha"] = "portugal",
  ["town:portugal:evora"] = "portugal",
  ["town:portugal:faro"] = "portugal",
  ["town:portugal:leiria"] = "portugal",
  ["town:prussia:tannenberg"] = "prussia",
  ["town:prussia:tilsit"] = "prussia",
  ["town:punjab:kasur"] = "punjab",
  ["town:punjab:khanpur"] = "punjab",
  ["town:punjab:multan"] = "punjab",
  ["town:punjab:rawalpindi"] = "punjab",
  ["town:rajpootana:jeypore"] = "rajpootana",
  ["town:rajpootana:jodhpur"] = "rajpootana",
  ["town:rajpootana:shahpura"] = "rajpootana",
  ["town:rhineland:cassel"] = "rhineland",
  ["town:rhineland:frankfurt"] = "rhineland",
  ["town:rhineland:marburg"] = "rhineland",
  ["town:rhineland:munster"] = "rhineland",
  ["town:rumelia:adrianople"] = "rumelia",
  ["town:rumelia:kozani"] = "rumelia",
  ["town:rumelia:skopje"] = "rumelia",
  ["town:ruperts_land:fort_rupert"] = "ruperts_land",
  ["town:savoy:chambery"] = "savoy",
  ["town:savoy:chieri"] = "savoy",
  ["town:saxony:erfurt"] = "saxony",
  ["town:saxony:leipzig"] = "saxony",
  ["town:scotland:dundee"] = "scotland",
  ["town:scotland:inverness"] = "scotland",
  ["town:serbia:nis"] = "serbia",
  ["town:serbia:timisoara"] = "serbia",
  ["town:silesia:gleiwitz"] = "silesia",
  ["town:silesia:glogau"] = "silesia",
  ["town:sindh:larkana"] = "sindh",
  ["town:sindh:umarkot"] = "sindh",
  ["town:spain:andorra"] = "spain",
  ["town:spain:barcelona"] = "spain",
  ["town:spain:cordoba"] = "spain",
  ["town:spain:granada"] = "spain",
  ["town:spain:salamanca"] = "spain",
  ["town:spain:sevilla"] = "spain",
  ["town:sweden:gothenburg"] = "sweden",
  ["town:sweden:karlstad"] = "sweden",
  ["town:sweden:linkoping"] = "sweden",
  ["town:sweden:luleaa"] = "sweden",
  ["town:sweden:uppsala"] = "sweden",
  ["town:syria:aleppo"] = "syria",
  ["town:tatariya:azov"] = "tatariya",
  ["town:tatariya:saratov"] = "tatariya",
  ["town:tatariya:tsaritsyn"] = "tatariya",
  ["town:tatariya:voronezh"] = "tatariya",
  ["town:tejas:laredo"] = "tejas",
  ["town:the_papal_states:bologna"] = "the_papal_states",
  ["town:the_papal_states:florence"] = "the_papal_states",
  ["town:the_papal_states:siena"] = "the_papal_states",
  ["town:transylvania:gyulafehervar"] = "transylvania",
  ["town:transylvania:szatmarnemeti"] = "transylvania",
  ["town:tripoli:benghazi"] = "tripoli",
  ["town:tripoli:misratah"] = "tripoli",
  ["town:tunis:kasserine"] = "tunis",
  ["town:tunis:tataouine"] = "tunis",
  ["town:ukraine:kharkov"] = "ukraine",
  ["town:ukraine:poltava"] = "ukraine",
  ["town:upper_louisiana:fort_crevecoeur"] = "upper_louisiana",
  ["town:upper_louisiana:shikaakwa"] = "upper_louisiana",
  ["town:venice:udine"] = "venice",
  ["town:venice:verona"] = "venice",
  ["town:virginia:richmond"] = "virginia",
  ["town:west_pommerania:koslin"] = "west_pommerania",
  ["town:west_pommerania:magdeburg"] = "west_pommerania",
  ["town:west_pommerania:potsdam"] = "west_pommerania",
  ["town:west_pommerania:stettin"] = "west_pommerania",
  ["town:west_pommerania:wismar"] = "west_pommerania",
  ["town:west_prussia:bydgoszcz"] = "west_prussia",
  ["town:west_prussia:elblag"] = "west_prussia",
  ["town:west_prussia:poznan"] = "west_prussia",
  ["town:wurttemberg:heidelberg"] = "wurttemberg",
  ["town:wurttemberg:ulm"] = "wurttemberg",
  ["port:bijapur:vengurla"] = "bijapur",
  ["town:wilderness_khiva:ust_jick"] = "wilderness_khiva",
  ["town:wilderness_khiva:dashauz"] = "wilderness_khiva",
  ["gold:wilderness_khiva:busurulan"] = "wilderness_khiva",
  ["sheep:wilderness_khiva:nukus"] = "wilderness_khiva",
  ["rice:wilderness_khiva:astrabad"] = "wilderness_khiva"
}



-- Dictionary of artillery type to gun type
artilleryToGunType = {
	["12_lber_ship_fort_cannon"]="fort_12_pounder",
	["18_lber_ship_fort_cannon"]="fort_18_pounder",
	["episodic_2_24_lber_land_cannon"]="episodic_24_pounder",
	["episodic_demi_cannon"]="episodic_demi_cannon",
	["episodic_sakers"]="cannon_9_pounder_early",
	["12_lber_howitzer"]="howitzer_12_pounder",
	["12_lber_howitzer_colonial"]="howitzer_12_pounder",
	["12_lber_land_cannon"]="cannon_12_pounder",
	["12_lber_land_cannon_colonial"]="cannon_12_pounder",
	["12_lber_land_cannon_indian"]="ott_cannon_12_pounder",
	["18_lber_land_cannon"]="cannon_18_pounder",
	["18_lber_land_cannon_east"]="ott_cannon_18_pounder",
	["18_lber_land_cannon_guard_galloper"]="cannon_18_pounder",
	["18_lber_land_cannon_indian"]="ott_cannon_18_pounder",
	["24_lber_howitzer"]="howitzer_24_pounder",
	["24_lber_howitzer_ottoman"]="ott_howitzer_24_pounder",
	["24_lber_land_cannon"]="cannon_24_pounder",
	["24_lber_land_cannon_(demi_cannon)"]="cannon_24_pounder_early",
	["24_lber_land_cannon_(demi_cannon)_east"]="ott_cannon_24_pounder",
	["24_lber_land_cannon_(demi_cannon)_indian"]="ott_cannon_24_pounder",
	["24_lber_land_cannon_east"]="ott_cannon_24_pounder",
	["24_lber_land_cannon_guard"]="cannon_24_pounder",
	["24_lber_land_cannon_indian"]="ott_cannon_24_pounder",
	["24_lber_ship_fort_cannon"]="fort_24_pounder",
	["3_lber_land_cannon_galloper"]="cannon_3_pounder",
	["4_inch_mortar"]="mortar_4",
	["4_inch_mortar_indian"]="ott_mortar_4",
	["6_lber_land_cannon_galloper"]="cannon_6_pounder",
	["64_lber_fort_carronade"]="fort_carronade_64_pounder",
	["64_lber_land_cannon_elephant"]="siege_cannon_64_pounder",
	["64_lber_siege_cannon"]="siege_cannon_64_pounder",
	["8_inch_mortar"]="mortar_8",
	["8_inch_mortar_east"]="ott_mortar_8",
	["8_inch_mortar_indian"]="ott_mortar_8",
	["9_lber_land_cannon_(saker)"]="cannon_9_pounder_early",
	["9_lber_land_cannon_(saker)_east"]="ott_cannon_9_pounder",
	["9_lber_land_cannon_(saker)_indian"]="ott_cannon_9_pounder",
	["native_american_artillery"]="cannon_9_pounder_early",
	["puckle_gun"]="puckle",
	["rockets_camel"]="rockets_fixed",
	["rockets_fixed"]="rockets_fixed",
	["sp_ed_organ_gun"]="ottoman_great_cannon",
	["z_andy_test"]="naval_12_pounder",
	["ottoman_great_cannon"]="ottoman_great_cannon",
}

